### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by edwbuck**

### CODE REVIEW

**Comment by edwbuck** [comment]
Please review and then squash and merge.

To see the impact of these changes, https://github.com/edwbuck/helm-charts-flex/tree/readme_udpates

**Comment by edwbuck** [comment]
@kfox1111 Please review this for a squash and merge today.  Take care to modify the commit message in the squash and merge appropriately.

**Comment by kfox1111** [comment]
> @kfox1111 Please review this for a squash and merge today. Take care to modify the commit message in the squash and merge appropriately.

Was waiting on the name question from the other review. That's resolved now. Only thing I can see here to fix is the chart name doesn't match what is being created in the other pr?

**Review by kfox1111 — APPROVED** [review]
LGTM

**Pull request merged**
